### PR TITLE
Fixes issue #501

### LINKED ISSUE #501: Swift: InvocationTargetException due to cleanup-*/database-* files
Downloading data from the repo using the swift plugin fails with an exception (`sy down` and `sy ls-remote` commands for example).

As an example, with `sy down` I get the following:
```
21-7-15 23:44:22.566 | RetriableFeatur | main           | WARN : Transfer method failed. 1/3 retries. Sleeping 3000ms ...
org.syncany.plugins.transfer.StorageException: java.lang.reflect.InvocationTargetException
        at org.syncany.plugins.transfer.files.RemoteFile.createRemoteFile(RemoteFile.java:130)
        at org.syncany.plugins.swift.SwiftTransferManager.list(SwiftTransferManager.java:208)
        at org.syncany.plugins.transfer.features.RetriableFeatureTransferManager$8.execute(RetriableFeatureTransferManager.java:146)
        at org.syncany.plugins.transfer.features.RetriableFeatureTransferManager.retryMethod(RetriableFeatureTransferManager.java:210)
        at org.syncany.plugins.transfer.features.RetriableFeatureTransferManager.list(RetriableFeatureTransferManager.java:143)
        at org.syncany.plugins.transfer.features.TransactionAwareFeatureTransferManager.list(TransactionAwareFeatureTransferManager.java:148)
        at org.syncany.operations.down.DownOperation.getRemoteCleanupFiles(DownOperation.java:695)
        at org.syncany.operations.down.DownOperation.execute(DownOperation.java:156)
        at org.syncany.cli.DownCommand.execute(DownCommand.java:56)
        at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:392)
        at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:382)
        at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:198)
        at org.syncany.Syncany.main(Syncany.java:52)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.syncany.plugins.transfer.files.RemoteFile.createRemoteFile(RemoteFile.java:127)
        ... 12 more
Caused by: org.syncany.plugins.transfer.StorageException: database-LZeYqizikbLuMEnWGPBK-0000000004: remote filename pattern does not match: cleanup-([0-9]+) expected.
        at org.syncany.plugins.transfer.files.CleanupRemoteFile.validateName(CleanupRemoteFile.java:64)
        at org.syncany.plugins.transfer.files.RemoteFile.<init>(RemoteFile.java:73)
        at org.syncany.plugins.transfer.files.CleanupRemoteFile.<init>(CleanupRemoteFile.java:46)
        ... 17 more
```

The issue seems to be that in [SwiftTransferManager.java:228](https://github.com/syncany/syncany-plugin-swift/blob/develop/src/main/java/org/syncany/plugins/swift/SwiftTransferManager.java#L228) `SwiftTransferManager.getRemoteFilePath()` returns the same `/databases` path for both `cleanup-*` and `database-*` files. `SwiftTransferManager.list()` then gets confused at [SwiftTransferManager.java:212](https://github.com/syncany/syncany-plugin-swift/blob/develop/src/main/java/org/syncany/plugins/swift/SwiftTransferManager.java#L212) since it gets both `cleanup-*` and `database-*` files from the listing, but expects them to be of the specified type.

Versions:
 * Syncany: 0.4.6-alpha (from the deb package)
 * Swift plugin: 0.4.0-alpha from the repos + compiled the develop branch myself

### PR DESCRIPTION
**Pull request by liamjack**
This pull request fixes [issue 501](https://github.com/syncany/syncany/issues/501) by catching the Exception that is generated the same way [the S3 plugin does it](https://github.com/syncany/syncany-plugin-s3/blob/develop/src/main/java/org/syncany/plugins/s3/S3TransferManager.java#L323)

`sy down` now works as intended !

### CODE REVIEW

**Comment by pimotte** [comment]
Looks good to me. This PR now supersedes #3. 

If there are no other comments before sunday I'll do a merge and plugin release then.

**Comment by liamjack** [comment]
Great, thanks !

**Comment by pimotte** [comment]
Just wanted to let you know that I haven't forgotten about this, but issues 533/534, and the fact that our build will break on the next PR, has higher priority. (It might even cause the plugin build to break, so I want to fix that before merging.)

**Comment by liamjack** [comment]
Sure thing no problem, they are definitely high priority, I have the same problem as  #533, I originally thought that I had misconfigured something.

**Comment by pimotte** [comment]
Do you have any logs to allow us to investigate?

**Comment by liamjack** [comment]
Sent via email

**Comment by binwiederhier** [comment]
@cuonic So can this be merged like this? 4 of the 5 commits are already in 'develop'. Once this is merged I'll merge it into 'master' to to create 0.4.1

**Comment by pimotte** [comment]
Feel free to merge. I was holding off on this became I wanted to focus on the build/deletion issues, but it should be good to go.

**Comment by liamjack** [comment]
@binwiederhier This is the develop branch + a fix for an issue that made the plugin useless, I put it in another branch based on @pimotte's recommendation.

**Comment by binwiederhier** [comment]
@cuonic Ok merged. Once the build is done, can you check if `sy plugin install swift --snapshot` works for you. I'll then make a new release.

**Comment by liamjack** [comment]
Can confirm, works perfectly !

**Pull request merged**
